name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Nintendo DS ROM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM GCC Toolchain & Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Build DSMeteo ROM
        run: |
          make clean
          make

      - name: Upload DSMeteo NDS ROM
        uses: actions/upload-artifact@v4
        with:
          name: DSMeteo-nds
          path: DSMeteo.nds
