name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Nintendo DSi ROM
    runs-on: ubuntu-latest
    container:
      image: skylyrac/blocksds:slim-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build DSMeteo ROM
        run: |
          make clean || true
          make

      - name: Upload DSMeteo NDS ROM
        uses: actions/upload-artifact@v4
        with:
          name: DSMeteo-nds
          path: DSMeteo.nds
