name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Nintendo DSi ROM with BlocksDS
        uses: docker://blocksds/sdk:latest
        with:
          args: make

      - name: Upload DSMeteo NDS ROM
        uses: actions/upload-artifact@v4
        with:
          name: DSMeteo-nds
          path: DSMeteo.nds
